apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-gateway-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kubernetes-sigs/gateway-api/'
    targetRevision: v1.1.0
    path: ./config/crd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
