apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'cnoe://'
    targetRevision: HEAD
    path: ./apps/ingress-gateway
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
